
alunos = [
    'ARTHUR AZEVEDO DUARTE',
    'FILIPE CENTENO DA ROCHA',
    'GABRIEL CASTRO COSTA',
    'ISABELLA ROSA MARTINS',
    'JOÃO ROBERTO JORGE BORGES NETO',
    'JULIA MARTINS GREGORIO',
    'LEONARDO CORREA DE SENA',
    'LUCAS ANDERSON BARBOSA',
    'PAOLLA DA SILVA VARELA',
    'RAFAEL PEREIRA DOS SANTOS'
]

presentes = [
    'GREICE BRAGA PEREIRA',
    'RAFAELA PRIETSCH DOS SANTOS',
    'ARTHUR GONÇALVES COSTA',
    'ARTUR DE OLIVEIRA COSTA',
    'EDUARDA SILVEIRA SCHROEDER',
    'GABRIEL MARQUES CANTO',
    'GABRIEL RODRIGUES',
    'JÉSSICA JANUÁRIO DOS SANTOS VILLAS BÔAS',
    'MARIA LUISA MARQUES DA SILVA',
    'MAURO SOUZA DA ROSA',
    'PEDRO EDUARDO DA SILVA PROTAS DOS SANTOS',
    'PEDRO FERREIRA DA SILVEIRA',
    'PEDRO HENRIQUE ROCHA OLIVEIRA',
    'THIAGO DE OLIVEIRA SOPEÑA',
    'WENDEL DE LEMOS COELHO',
    'YZA ROCHA DE LIMA'
]

presentes.shuffle!

until presentes.empty?
    p presentes.pop 2
end